//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Security;

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage",
            "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employer()
        {
            this.emp_dep = new HashSet<emp_dep>();
            this.emp_tec_route = new HashSet<emp_tec_route>();
        }

        public int id_passport { get; set; }
        public string name_emp { get; set; }
        public string adress { get; set; }
        public string telephone { get; set; }
        public string status_ { get; set; }
        public string login_ { get; set; }
        [DataType(DataType.Password)] public string password_ { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage",
            "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_dep> emp_dep { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage",
            "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_tec_route> emp_tec_route { get; set; }

    }
}
