//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_apply
    {
        public int id_apply { get; set; }
        public int id_passport { get; set; }
        public string name_j_apply { get; set; }
        public string name_prof { get; set; }
        public string telephone { get; set; }
        public string info_j_apply { get; set; }
    }
}
